/*
 * Objective.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "Objective.h"
#include "compObjective.h"
// Start of user code  : Additional imports for Objective
// End of user code


Objective::Objective(compObjective *container)	{
		myContainer = container;
// Start of user code  : Implementation of constructor method

// End of user code
	}
Objective::~Objective(){
// Start of user code  : Implementation of destructor method

// End of user code
	}
void Objective::initialize() {
// Start of user code  : Implementation of initialize method

// End of user code
	}

void Objective::end() {
// Start of user code  : Implementation of end method

// End of user code
	}

void Objective::doStep(int nStep) {
// Start of user code  : Implementation of doStep method
		// to implement
// End of user code
	}
	
	// +++++++++++++ Methods of the pItfTargetObject interface +++++++++++++
bool Objective::isObjectNear(){
// Start of user code  : Implementation of method isObjectNear
		// to implement
// End of user code
	}

	
// Start of user code  : Additional methods

// End of user code
	

	// +++++++++++++ Access for speed parameter +++++++++++++
double Objective::getSpeed() {
		return speed;
	}
	
void Objective::setSpeed(double arg) {
		speed = arg;
	}
	// +++++++++++++ Access for position parameter +++++++++++++
vect2 Objective::getPosition() {
		return position;
	}
	
void Objective::setPosition(vect2 arg) {
		position = arg;
	}

