/* 
 * Scenario implementation
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#include "ScenarLog.h"
#include "Clock.h"

ScenarLog::ScenarLog(RootComponent* aRoot) : Scenario(aRoot) {
    root = aRoot;
    application = (DroSimSystem*)aRoot;
}

ScenarLog::~ScenarLog() {}

void ScenarLog::eventSimulation() {
    Clock* c = Clock::getInstance();
    //long currentTime = c->getCurrentMS();
}
