/*
 * DroneData
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#include "DroneData.h"
// Start of user code  : Additional imports for DroneData
// End of user code

DroneData::DroneData() {
	}
DroneData::~DroneData() {
	}

DroneData::DroneData( long varstrategy, long varID, bool varhasFound) {
		strategy = varstrategy;
		ID = varID;
		hasFound = varhasFound;
	}

long DroneData::getStrategy () {
		return strategy ;
	}

void DroneData::setStrategy (long varstrategy ) {
		strategy  = varstrategy ;
	}

long DroneData::getID () {
		return ID ;
	}

void DroneData::setID (long varID ) {
		ID  = varID ;
	}

bool DroneData::getHasFound () {
		return hasFound ;
	}

void DroneData::setHasFound (bool varhasFound ) {
		hasFound  = varhasFound ;
	}

// Start of user code  : Additional methods

// End of user code


