/*
 * myPositionsLogLogObservationComponent
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef myPositionsLogLogObservationComponent_H_
#define myPositionsLogLogObservationComponent_H_

#include "LogComponent.h"
using namespace std;
#include "Objective.h"
#include "DroneSweep.h"
#include "Vect2.h"

class myPositionsLogLogObservationComponent : public LogComponent {
    //pyp : LeafComponent qui genere les donnees sur le port (OutputPort) 
protected :
    Objective* theObjective;
    vector<DroneSweep*> theDroneSweep;
    //pyp : variables permettant de recuperer les donnees lues
    vect2 instObjposition;
    vector<vect2> instSweepposition;

private :
    bool first = true;

public :
    myPositionsLogLogObservationComponent(string filename, double aFrequency);
    virtual ~myPositionsLogLogObservationComponent();
    void readInputs();
    void WriteFirstLine();

    void setObjective(Objective* myObjective);
    void setDroneSweep(vector<DroneSweep*> myDroneSweep);
    void doStep(int nStep);
};
#endif /* myPositionsLogLogObservationComponent */
