/*
 * mySwimmerPositionLogObservationComponent
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef mySwimmerPositionLogObservationComponent_H_
#define mySwimmerPositionLogObservationComponent_H_

#include "Clock.h"
#include "LogComponent.h"
#include <fstream>
using namespace std;
#include "DroneSweep.h"
#include "DroneSpiral.h"
#include "Objective.h"
#include "DroneData.h"
#include "DroneData.h"

class mySwimmerPositionLogObservationComponent : public LogComponent {
	
	//pyp : LeafComponent qui g�n�re les donn�es sur le port (OutputPort) 
	protected :
    	DroneSweep  *theDroneSweep;
    	DroneSpiral  *theDroneSpiral;
    	Objective  *theObjective;
		//pyp : variables permettant de r�cup�rer les donn�es lues
		DroneData instDroneData;
		DroneData instDroneData;
		double instObjposX;
		double instObjposY;

	
	private :
		bool first = true;
	
	public :
	    mySwimmerPositionLogObservationComponent(string filename, double aFrequency);
	    virtual ~mySwimmerPositionLogObservationComponent();
		void readInputs();
		void WriteFirstLine();

		void setDroneSweep(DroneSweep *myDroneSweep);
		void setDroneSpiral(DroneSpiral *myDroneSpiral);
		void setObjective(Objective *myObjective);
		void doStep(int nStep);
};
#endif /* mySwimmerPositionLogObservationComponent */
