/*
 * compUser.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef compUser_H_
#define compUser_H_

#include "LeafComponent.h"
class User;



#include "ItfManageSimInterface.h"

class compUser : public LeafComponent  , public ItfManageSimInterface {

	protected :
/*pyp : inutile
*/

	 bool newValue;
	 int delay;


	User *appli;

	public :
           compUser(double aFrequency);
           virtual ~compUser();
	       void doOneStep();
	       void doStep(int nStep);

	       virtual void readInputs() ;
	       void initialize();
	       void end();
	
	// +++++++++++++ Methods of the pItfManageSimulation interface +++++++++++++
	      void signalObjectiveFound(long droneID);

	     User *getAppli() ;
};
#endif /* compUser_H_ */
