/*
 * compGeoZone.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef compGeoZone_H_
#define compGeoZone_H_

#include "LeafComponent.h"
class GeoZone;

#include "vect2.h"

#include "ItfGeoDataInterface.h"
#include "wect2.h"

class compGeoZone : public LeafComponent, public ItfGeoDataInterface {
protected :
    /*pyp : inutile
    */

    bool newValue;
    int delay;


    GeoZone* appli;

public :
    compGeoZone(double aFrequency);
    virtual ~compGeoZone();
    void doOneStep();
    void doStep(int nStep);

    virtual void readInputs();
    void initialize();
    void end();

    // +++++++++++++ Methods of the pItfGeoData interface +++++++++++++
    vect2 grabEnvLimits();

    wect2 grabAssignedZone(long droneID);

    GeoZone* getAppli();
    // +++++++++++++ Access for envSize parameter +++++++++++++
    vect2 getEnvSize();

    void setEnvSize(vect2 arg);
    // +++++++++++++ Access for maxInlineZones parameter +++++++++++++
    long getMaxInlineZones();

    void setMaxInlineZones(long arg);
    // +++++++++++++ Access for bottomLeftPoint parameter +++++++++++++
    vect2 getBottomLeftPoint();

    void setBottomLeftPoint(vect2 arg);
    long getDroneCount();
    void setDroneCount(long arg);
};
#endif /* compGeoZone_H_ */
