/*
 * compObjective.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef compObjective_H_
#define compObjective_H_

#include "LeafComponent.h"
class Objective;

#include "vect2.h"
#include "vect2.h"


#include "ItfEnvironmentInterface.h"
#include "vect2.h"
#include "wect2.h"

class compObjective : public LeafComponent {

	protected :
/*pyp : inutile
*/
	 vect2 oldObjposition;
	 vect2 newObjposition;

	 bool newValue;
	 int delay;


	Objective *appli;

	public :
           compObjective(double aFrequency);
           virtual ~compObjective();
	       void doOneStep();
	       void doStep(int nStep);

	       virtual void readInputs() ;
	       void initialize();
void lateinitialize();
void end();
	
	     vect2 getObjposition();
	     void setrItfEnvironmentObj(ItfEnvironmentInterface *arItfEnvironmentObj);
	     Objective *getAppli() ;
	// +++++++++++++ Access for speed parameter +++++++++++++
	     double getSpeed();
	
	     void setSpeed(double arg);
	// +++++++++++++ Access for position parameter +++++++++++++
	     vect2 getPosition();
	
	     void setPosition(vect2 arg);
};
#endif /* compObjective_H_ */
