/*
 * compEnvironment.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef compEnvironment_H_
#define compEnvironment_H_

#include "LeafComponent.h"
class Environment;

#include "vect2.h"


#include "ItfEnvironmentInterface.h"
#include "vect2.h"
#include "wect2.h"

class compEnvironment : public LeafComponent  , public ItfEnvironmentInterface {

	protected :
/*pyp : inutile
*/

	 bool newValue;
	 int delay;


	Environment *appli;

	public :
           compEnvironment(double aFrequency);
           virtual ~compEnvironment();
	       void doOneStep();
	       void doStep(int nStep);

	       virtual void readInputs() ;
	       void initialize();
	       void end();
	
	// +++++++++++++ Methods of the pItfEnvironment interface +++++++++++++
	      vect2 getEnvLimits();

	      wect2 getAssignedZone(long ID);

	     Environment *getAppli() ;
	// +++++++++++++ Access for envSize parameter +++++++++++++
	     vect2 getEnvSize();
	
	     void setEnvSize(vect2 arg);
	// +++++++++++++ Access for maxInlineZones parameter +++++++++++++
	     long getMaxInlineZones();
	
	     void setMaxInlineZones(long arg);
	// +++++++++++++ Access for sweepNumber parameter +++++++++++++
	     long getSweepNumber();
	
	     void setSweepNumber(long arg);
	// +++++++++++++ Access for spiralNumber parameter +++++++++++++
	     long getSpiralNumber();
	
	     void setSpiralNumber(long arg);
};
#endif /* compEnvironment_H_ */
