/*
 * compUser.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef compUser_H_
#define compUser_H_

#include "ItfGeoDataInterface.h"
#include "LeafComponent.h"
#include "ReturnCode.h"
#include "wect2.h"
class User;


#include "ItfManageSimInterface.h"

class compUser : public LeafComponent, public ItfManageSimInterface {
protected :
    bool newValue;
    int delay;

    User* appli;

public :
    compUser(double aFrequency);
    virtual ~compUser();
    void doOneStep();
    ReturnCode doStep(int nStep) override;

    virtual void readInputs();
    void initialize();
    void end();

    void setrItfGeoDataUser(ItfGeoDataInterface* arItfGeoDataUser);

    // +++++++++++++ Methods of the pItfManageSimulation interface +++++++++++++
    void signalObjectiveFound(long droneID) override;
    wect2 grabAssignedZone(long droneID) override;

    User* getAppli();

    // +++++++++++++ Access for droneCount calculated attribute +++++++++++++
    long getDroneCount();

    void setDroneCount(long arg);
};
#endif /* compUser_H_ */
