/*
 * compObjective.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef compObjective_H_
#define compObjective_H_

#include "LeafComponent.h"
class Objective;

#include "vect2.h"


#include "ItfTargetObjectInterface.h"

class compObjective : public LeafComponent  , public ItfTargetObjectInterface {

	protected :
/*pyp : inutile
*/

	 bool newValue;
	 int delay;


	Objective *appli;

	public :
           compObjective(double aFrequency);
           virtual ~compObjective();
	       void doOneStep();
	       void doStep(int nStep);

	       virtual void readInputs() ;
	       void initialize();
	       void end();
	
	// +++++++++++++ Methods of the pItfTargetObject interface +++++++++++++
	      bool isObjectNear();

	     Objective *getAppli() ;
	// +++++++++++++ Access for speed parameter +++++++++++++
	     double getSpeed();
	
	     void setSpeed(double arg);
	// +++++++++++++ Access for position parameter +++++++++++++
	     vect2 getPosition();
	
	     void setPosition(vect2 arg);
};
#endif /* compObjective_H_ */
