/*
 * compWind.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef compWind_H_
#define compWind_H_

#include "LeafComponent.h"
class Wind;

#include "vect2.h"

#include "ItfWindForceInterface.h"

class compWind : public LeafComponent, public ItfWindForceInterface {
protected :
    /*pyp : inutile
    */

    bool newValue;
    int delay;


    Wind* appli;

public :
    compWind(double aFrequency);
    virtual ~compWind();
    void doOneStep();
    void doStep(int nStep);

    virtual void readInputs();
    void initialize();
    void end();

    // +++++++++++++ Methods of the pItfWindForce interface +++++++++++++
    double grabForce();

    vect2 grabDirection();

    Wind* getAppli();
    // +++++++++++++ Access for force parameter +++++++++++++
    double getForce();

    void setForce(double arg);
    // +++++++++++++ Access for direction parameter +++++++++++++
    vect2 getDirection();

    void setDirection(vect2 arg);
};
#endif /* compWind_H_ */
