/*
 * compGeoZone.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef compGeoZone_H_
#define compGeoZone_H_

#include "LeafComponent.h"
class GeoZone;

#include "vect2.h"

#include "ItfGeoDataInterface.h"
#include "wect2.h"

class compGeoZone : public LeafComponent, public ItfGeoDataInterface {
protected :
    bool newValue;
    int delay;

    string name = "GeoZone";
    
    GeoZone* appli;

public :
    compGeoZone(double aFrequency);
    virtual ~compGeoZone();
    void doOneStep();
    int doStep(int nStep);

    virtual void readInputs();
    void initialize();
    void end();

    string getName() { return name; }
    GeoZone* getAppli();

    // +++++++++++++ Methods of the pItfGeoData interface +++++++++++++
    vect2 grabEnvLimits() override;
    vect2 grabBottomLeftPoint() override;
    
    // +++++++++++++ Access for envSize parameter +++++++++++++
    vect2 getEnvSize();

    void setEnvSize(vect2 arg);
    // +++++++++++++ Access for bottomLeftPoint parameter +++++++++++++
    vect2 getBottomLeftPoint();

    void setBottomLeftPoint(vect2 arg);
};
#endif /* compGeoZone_H_ */
