/*
 * compManager.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef compManager_H_
#define compManager_H_

#include "LeafComponent.h"
class Manager;



#include "ItfManagerInterface.h"

class compManager : public LeafComponent  , public ItfManagerInterface {

	protected :
/*pyp : inutile
*/

	 bool newValue;
	 int delay;


	Manager *appli;

	public :
           compManager(double aFrequency);
           virtual ~compManager();
	       void doOneStep();
	       void doStep(int nStep);

	       virtual void readInputs() ;
	       void initialize();
	       void end();
	
	// +++++++++++++ Methods of the pItfManager interface +++++++++++++
	      void signalObjectiveFound(long droneID);

	     Manager *getAppli() ;
	// +++++++++++++ Access for expectedEndTime parameter +++++++++++++
	     double getExpectedEndTime();
	
	     void setExpectedEndTime(double arg);
};
#endif /* compManager_H_ */
