/*
 * compWind.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef compWind_H_
#define compWind_H_

#include "LeafComponent.h"
#include "ReturnCode.h"
class Wind;

#include "vect2.h"

class compWind : public LeafComponent {
protected :
    double oldWindForce;
    double newWindForce;
    vect2 oldWindDirection;
    vect2 newWindDirection;
    
    bool newValue;
    int delay;

    Wind* appli;

public :
    compWind(double aFrequency);
    virtual ~compWind();
    void doOneStep();
    ReturnCode doStep(int nStep);

    virtual void readInputs();
    void initialize();
    void end();

    double getWindForce();
    vect2 getWindDirection();
    Wind* getAppli();
    
    // +++++++++++++ Access for force parameter +++++++++++++
    double getForce();

    void setForce(double arg);
    // +++++++++++++ Access for direction parameter +++++++++++++
    vect2 getDirection();

    void setDirection(vect2 arg);
};
#endif /* compWind_H_ */
