/*
 * compDroneSweep.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef compDroneSweep_H_
#define compDroneSweep_H_

#include "DroneSweep.h"
#include "LeafComponent.h"
class DroneSweep;

#include "vect2.h"

#include "ItfGeoDataInterface.h"
#include "ItfManageSimInterface.h"
#include "ItfSimDataInterface.h"

#include <unordered_map>

class compDroneSweep : public LeafComponent {
protected :
    vector<DroneSweep*> appli;
    unordered_map<int,bool> status;
    vector<vect2> oldSweepposition;
    vector<vect2> newSweepposition;

    bool newValue;
    int delay;

public :
    compDroneSweep(double aFrequency);
    virtual ~compDroneSweep();
    void doOneStep();
    int doStep(int nStep);
    int sendReturnCode(const vector<int>& returnCodes);
    bool pauseCondition(DroneSweep* inst);
    void updateNumberOfInstances(const unsigned int arg);
    void printInstRecap();

    virtual void readInputs();
    void initialize();
    void end();

    vector<vect2> getSweepposition();
    void setrItfGeoDataSweep(ItfGeoDataInterface* arItfGeoDataSweep);
    void setrItfManageSimSweep(ItfManageSimInterface* arItfManageSimSweep);
    void setrItfSimDataSweep(ItfSimDataInterface* arItfSimDataSweep);
    vector<DroneSweep*> getAppli();

    double getSpeed() { return appli[0]->getSpeed(); }
    void setSpeed(double arg) { for (DroneSweep* obj : appli) obj->setSpeed(arg); }
    int getBatteryCount() { return appli[0]->getBatteryCount(); }
    void setBatteryCount(int arg) { for (DroneSweep* obj : appli) obj->setBatteryCount(arg); }
    
    // +++++++++++++ Access for minSpeed parameter +++++++++++++
    double getMinSpeed();

    void setMinSpeed(double arg);
    // +++++++++++++ Access for minSpeed parameter +++++++++++++
    double getMaxSpeed();

    void setMaxSpeed(double arg);
    // +++++++++++++ Access for visionRadius parameter +++++++++++++
    double getVisionRadius();

    void setVisionRadius(double arg);
    // +++++++++++++ Access for sweepHeight parameter +++++++++++++
    double getSweepHeight();

    void setSweepHeight(double arg);
    // +++++++++++++ Access for batteryCapacity parameter +++++++++++++
    double getBatteryCapacity();

    void setBatteryCapacity(double arg);
    // +++++++++++++ Access for numberOf parameter +++++++++++++
    long getNumberOf();

    void setNumberOf(long arg);
    // +++++++++++++ Access for startingPoint parameter +++++++++++++
    vect2 getStartingPoint();

    void setStartingPoint(vect2 arg);
    // +++++++++++++ Access for collisionRadius parameter +++++++++++++
    double getCollisionRadius();

    void setCollisionRadius(double arg);
};
#endif /* compDroneSweep_H_ */
