/*
 * compManager.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef compManager_H_
#define compManager_H_

#include "LeafComponent.h"
class Manager;

#include "ItfManageSimInterface.h"

class compManager : public LeafComponent, public ItfManageSimInterface {
protected :
    /*pyp : inutile
    */

    bool newValue;
    int delay;


    Manager* appli;

public :
    compManager(double aFrequency);
    virtual ~compManager();
    void doOneStep();
    void doStep(int nStep);

    virtual void readInputs();
    void initialize();
    void end();

    // +++++++++++++ Methods of the pItfManageSimulation interface +++++++++++++
    void signalObjectiveFound(long droneID);

    Manager* getAppli();
};
#endif /* compManager_H_ */
