/*
 * compDroneSweep.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef compDroneSweep_H_
#define compDroneSweep_H_

#include "LeafComponent.h"
class DroneSweep;

#include "vect2.h"

#include "ItfGeoDataInterface.h"
#include "ItfWindForceInterface.h"
#include "ItfManageSimInterface.h"
#include "ItfSimDataInterface.h"

class compDroneSweep : public LeafComponent {
protected :
    /*pyp : inutile
        //inputs source
         LeafComponent ObjpositionSourceComponent;
         String portNameObjposition;
    */
    vector<DroneSweep*> appli;
    vector<vect2> oldSweepposition;
    vector<vect2> newSweepposition;

    bool newValue;
    int delay;

public :
    compDroneSweep(double aFrequency, long numberOf);
    virtual ~compDroneSweep();
    void doOneStep();
    void doStep(int nStep);

    virtual void readInputs();
    void initialize();
    void end();

    vector<vect2> getSweepposition();
    void setrItfGeoDataSweep(ItfGeoDataInterface* arItfGeoDataSweep);
    void setrItfWindForceSweep(ItfWindForceInterface* arItfWindForceSweep);
    void setrItfManageSimSweep(ItfManageSimInterface* arItfManageSimSweep);
    void setrItfSimDataSweep(ItfSimDataInterface* arItfSimDataSweep);
    vector<DroneSweep*> getAppli();
    // +++++++++++++ Access for speedConstraint parameter +++++++++++++
    double getSpeedConstraint();

    void setSpeedConstraint(double arg);
    // +++++++++++++ Access for visionRadius parameter +++++++++++++
    double getVisionRadius();

    void setVisionRadius(double arg);
    // +++++++++++++ Access for sweepHeight parameter +++++++++++++
    double getSweepHeight();

    void setSweepHeight(double arg);
    // +++++++++++++ Access for batteryCapacity parameter +++++++++++++
    double getBatteryCapacity();

    void setBatteryCapacity(double arg);
    // +++++++++++++ Access for numberOf parameter +++++++++++++
    long getNumberOf();

    void setNumberOf(long arg);
    // +++++++++++++ Access for startingPoint parameter +++++++++++++
    vect2 getStartingPoint();

    void setStartingPoint(vect2 arg);
};
#endif /* compDroneSweep_H_ */
