/* 
 * ADroneSpiral.h
 * Root Component
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef ADroneSpiral_H_
#define ADroneSpiral_H_

#include "compDroneSpiral.h"
#include "AObjective.h"
class AObjective;

class ADroneSpiral : public compDroneSpiral {
protected :
    AObjective* attAObjective;

public :
    ADroneSpiral(double aFrequency);
    virtual ~ADroneSpiral();

    void setAObjective(AObjective* pAObjective);

    void readInputs() override;
};
#endif /*  ADroneSpiral_H_ */
