/* 
 * ADroneSweep.h
 * Root Component
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef ADroneSweep_H_
#define ADroneSweep_H_

#include "compDroneSweep.h"
#include "AObjective.h"
class AObjective;

class ADroneSweep : public compDroneSweep {
	protected :
              AObjective *attAObjective;

	public :

            ADroneSweep(double aFrequency, long numberOf);
            virtual ~ADroneSweep();

	        void setAObjective(AObjective *pAObjective);

	        void readInputs()  override;
};
#endif /*  ADroneSweep_H_ */
