/* 
 * ADroneSpiral.h
 * Root Component
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef ADroneSpiral_H_
#define ADroneSpiral_H_

#include "compDroneSpiral.h"

class ADroneSpiral : public compDroneSpiral {
	protected :

	public :

            ADroneSpiral(double aFrequency);
            virtual ~ADroneSpiral();


	        void readInputs()  override;
};
#endif /*  ADroneSpiral_H_ */
