/* 
 * AEnvironment.h
 * Root Component
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef AEnvironment_H_
#define AEnvironment_H_

#include "compEnvironment.h"

class AEnvironment : public compEnvironment {
	protected :

	public :

            AEnvironment(double aFrequency);
            virtual ~AEnvironment();


	        void readInputs()  override;
};
#endif /*  AEnvironment_H_ */
