/* 
 * AManager.h
 * Root Component
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef AManager_H_
#define AManager_H_

#include "compManager.h"

class AManager : public compManager {

public :
    AManager(double aFrequency);
    virtual ~AManager();


    void readInputs() override;
};
#endif /*  AManager_H_ */
