/* 
 * AUser.h
 * Root Component
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef AUser_H_
#define AUser_H_

#include "compUser.h"

class AUser : public compUser {
	protected :

	public :

            AUser(double aFrequency);
            virtual ~AUser();


	        void readInputs()  override;
};
#endif /*  AUser_H_ */
