/* 
 * AWind.h
 * Root Component
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef AWind_H_
#define AWind_H_

#include "compWind.h"

class AWind : public compWind {
	protected :

	public :

            AWind(double aFrequency);
            virtual ~AWind();


	        void readInputs()  override;
};
#endif /*  AWind_H_ */
