/* 
 * DroSimSystem.java
 * Root Component
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef DroSimSystem_H_
#define DroSimSystem_H_

//#include <vector>
//#include "LeafComponent.h"
#include "RootComponent.h"

#include "ASimulation.h"
#include "AWind.h"
#include "AUser.h"
#include "AGeoZone.h"
#include "AObjective.h"
#include "ADroneSweep.h"
#include "ADroneSpiral.h"
// Start of user code  : Additional imports for DroSimSystem
#include <tuple>
// End of user code

class DroSimSystem : public RootComponent {
    // generated pointers on child leafComponents
protected :
    ASimulation* instASimulation;
    AWind* instAWind;
    AUser* instAUser;
    AGeoZone* instAGeoZone;
    AObjective* instAObjective;
    vector<ADroneSweep*> instADroneSweep;
    vector<ADroneSpiral*> instADroneSpiral;

    int mutableNumberOfDroneSweep = 0;
    int mutableNumberOfDroneSpiral = 1;

    double mutableSpeed;
    
    double minSpeed;
    double maxSpeed;
    int maxNumberOfDrones;
    double pSpeed = -1;
    int pNumberOfDroneSweep = -1;
    int pNumberOfDroneSpiral = -1;
    bool isCurveFound = false;
    bool isMaxFound = false;
    double speedIncrement;
    int numberOfDroneSweepIncrement;
    int numberOfDroneSpiralIncrement;

    vector<tuple<double,int,int>> slowConfigs;
    tuple<double,int,int> fastConfig;

public :
    DroSimSystem();
    virtual ~DroSimSystem();
    // generated getters of child leafComponents
    ASimulation* get_ASimulation();
    AWind* get_AWind();
    AUser* get_AUser();
    AGeoZone* get_AGeoZone();
    AObjective* get_AObjective();
    vector<ADroneSweep*> get_ADroneSweep();
    vector<ADroneSpiral*> get_ADroneSpiral();

    void initialize();

    void end();
    bool continueCondition() const;
    vector<tuple<double, int, int>> getSlowConfigs();
    tuple<double, int, int> getFastConfig();
    void mutateParameters(bool isGroupSuccessful, double averageTimeToFind);
};
#endif /*  DroSimSystem_H_ */
