/*
 * DroneSweep.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef DroneSweep_H_
#define DroneSweep_H_
class compDroneSweep;
// Inputs
#include "vect2.h"

#include "ItfGeoDataInterface.h"
#include "wect2.h"
#include "ItfWindForceInterface.h"
#include "ItfManageSimInterface.h"
#include "ItfSimDataInterface.h"

// Start of user code  : Additional imports for DroneSweep
// End of user code

class DroneSweep {
protected :
    compDroneSweep* myContainer;

    // Inputs
    vect2 objposition;
    // Outputs
    vect2 sweepposition;
    // Parameters
    double minSpeed;
    double maxSpeed;
    double visionRadius;
    double sweepHeight;
    double batteryCapacity;
    long numberOf;
    vect2 startingPoint;

    // Required Interfaces
    ItfGeoDataInterface* rItfGeoDataSweep;
    ItfWindForceInterface* rItfWindForceSweep;
    ItfManageSimInterface* rItfManageSimSweep;
    ItfSimDataInterface* rItfSimDataSweep;

    // Start of user code  : Properties of DroneSweep
protected:
    wect2 assignedZone;

private:
    string name = "DroneSweep";
    int droneID;
    double speed;
    vect2 position;
    vect2 direction;
    double batteryConsumption;
    double battery;
    double movementTolerance;
    bool goesVertical = true;
    bool leftToRight = false;
    bool topToBottom = false;
    long heightCount = 1;
    double sweepLength;
    double leftYBound;
    bool isInZone = false;
    vect2 zoneStartPoint;
    // End of user code

public :
    DroneSweep(compDroneSweep* container, int ID);
    ~DroneSweep();
    void initialize();
    void end();

    int doStep(int nStep);


    // Start of user code  : Additional methods
private:
    vect2 SetNextPosition();
    bool GoesOutOfBounds(vect2& point);

public:
    void setAssignedZone(wect2 zone);
    string getName() { return name; }
    double getSpeed() { return speed; }
    void setSpeed(double arg) { speed = arg; }
    // End of user code


    void setObjposition(vect2 arg);

    vect2 getSweepposition();
    void setrItfGeoDataSweep(ItfGeoDataInterface* arItfGeoDataSweep);
    void setrItfWindForceSweep(ItfWindForceInterface* arItfWindForceSweep);
    void setrItfManageSimSweep(ItfManageSimInterface* arItfManageSimSweep);
    void setrItfSimDataSweep(ItfSimDataInterface* arItfSimDataSweep);
    // +++++++++++++ Access for minSpeed parameter +++++++++++++
    double getMinSpeed();

    void setMinSpeed(double arg);
    // +++++++++++++ Access for minSpeed parameter +++++++++++++
    double getMaxSpeed();

    void setMaxSpeed(double arg);
    // +++++++++++++ Access for visionRadius parameter +++++++++++++
    double getVisionRadius();

    void setVisionRadius(double arg);
    // +++++++++++++ Access for sweepHeight parameter +++++++++++++
    double getSweepHeight();

    void setSweepHeight(double arg);
    // +++++++++++++ Access for batteryCapacity parameter +++++++++++++
    double getBatteryCapacity();

    void setBatteryCapacity(double arg);
    // +++++++++++++ Access for numberOf parameter +++++++++++++
    long getNumberOf();

    void setNumberOf(long arg);
    // +++++++++++++ Access for startingPoint parameter +++++++++++++
    vect2 getStartingPoint();

    void setStartingPoint(vect2 arg);
};
#endif /*  DroneSweep_H_ */
