/*
 * GeoZone.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef GeoZone_H_
#define GeoZone_H_
#include "ReturnCode.h"
class compGeoZone;
class DroSimSystem;
#include "vect2.h"

#include "ItfGeoDataInterface.h"

// Start of user code  : Additional imports for GeoZone
// End of user code

class GeoZone : public ItfGeoDataInterface {
protected :
    compGeoZone* myContainer;

    // Parameters
    vect2 envSize;
    vect2 bottomLeftPoint;

    DroSimSystem* systemRef_;

    // Start of user code  : Properties of GeoZone
    // End of user code

public :
    GeoZone(compGeoZone* container);
    ~GeoZone();
    void initialize();
    void end();

    ReturnCode doStep(int nStep);

    void setSystemRef(DroSimSystem* systemRef);

    // +++++++++++++ Methods of the pItfGeoData interface +++++++++++++
    vect2 grabEnvLimits() override;
    vect2 grabBottomLeftPoint() override;

    // Start of user code  : Additional methods
    // End of user code

    // +++++++++++++ Access for envSize parameter +++++++++++++
    vect2 getEnvSize();

    void setEnvSize(vect2 arg);
    // +++++++++++++ Access for bottomLeftPoint parameter +++++++++++++
    vect2 getBottomLeftPoint();

    void setBottomLeftPoint(vect2 arg);
};
#endif /*  GeoZone_H_ */
