/*
 * Manager.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef Manager_H_
#define Manager_H_
#include "Clock.h"
class compManager;

#include "ItfManageSimInterface.h"

// Start of user code  : Additional imports for Manager
// End of user code

class Manager : public ItfManageSimInterface {
protected :
    compManager* myContainer;


    // Start of user code  : Properties of Manager
    bool isObjectiveFound = false;
    // End of user code

public :
    Manager(compManager* container);
    ~Manager();
    void initialize();
    void end();

    void doStep(int nStep);

    // +++++++++++++ Methods of the pItfManageSimulation interface +++++++++++++
    void signalObjectiveFound(long droneID);


    // Start of user code  : Additional methods
    static double rand_range(double min, double max);
    // End of user code
};
#endif /*  Manager_H_ */
