/*
 * Objective.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef Objective_H_
#define Objective_H_
#include "Clock.h"
class compObjective;
#include "vect2.h"
#include "vect2.h"

#include "ItfGeoDataInterface.h"
#include "vect2.h"
#include "wect2.h"

// Start of user code  : Additional imports for Objective
// End of user code

class Objective {

	protected :
              compObjective *myContainer;

	// Outputs
	          vect2 objposition;
	// Parameters
	          double speedConstraint;
	          vect2 position;

	// Required Interfaces
	          ItfGeoDataInterface *rItfGeoDataObj;

// Start of user code  : Properties of Objective
    vect2 direction;
    double YLimit;
    // End of user code

	public :
            Objective(compObjective *container);
            ~Objective();
	        void initialize();
	       void end();

	       void doStep(int nStep) ;
	
	
// Start of user code  : Additional methods
    // End of user code
	

	    vect2 getObjposition();
	    void setrItfGeoDataObj(ItfGeoDataInterface *arItfGeoDataObj);
	// +++++++++++++ Access for speedConstraint parameter +++++++++++++
	    double getSpeedConstraint();
	
	    void setSpeedConstraint(double arg);
	// +++++++++++++ Access for position parameter +++++++++++++
	    vect2 getPosition();
	
	    void setPosition(vect2 arg);
};
#endif /*  Objective_H_ */
