/*
 * Objective.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef Objective_H_
#define Objective_H_
#include "Clock.h"
class compObjective;
#include "vect2.h"
#include "vect2.h"

#include "ItfEnvironmentInterface.h"
#include "vect2.h"
#include "wect2.h"

// Start of user code  : Additional imports for Objective
// End of user code

class Objective {

	protected :
              compObjective *myContainer;

	// Outputs
	          vect2 objposition;
	// Parameters
	          double speed;
	          vect2 position;

	// Required Interfaces
	          ItfEnvironmentInterface *rItfEnvironmentObj;

// Start of user code  : Properties of Objective
			  vect2 direction;
			  double YLimit;
// End of user code

	public :
            Objective(compObjective *container);
            ~Objective();
	        void initialize();
	       void end();

	       void doStep(int nStep) ;
	
	
// Start of user code  : Additional methods
	void lateinitialize();
// End of user code
	

	    vect2 getObjposition();
	    void setrItfEnvironmentObj(ItfEnvironmentInterface *arItfEnvironmentObj);
	// +++++++++++++ Access for speed parameter +++++++++++++
	    double getSpeed();
	
	    void setSpeed(double arg);
	// +++++++++++++ Access for position parameter +++++++++++++
	    vect2 getPosition();
	
	    void setPosition(vect2 arg);
};
#endif /*  Objective_H_ */
