/*
 * Objective.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef Objective_H_
#define Objective_H_
#include "Clock.h"
class compObjective;
#include "vect2.h"

#include "ItfTargetObjectInterface.h"

// Start of user code  : Additional imports for Objective
// End of user code

class Objective  : public ItfTargetObjectInterface {

	protected :
              compObjective *myContainer;

	// Parameters
	          double speed;
	          vect2 position;


// Start of user code  : Properties of Objective
// End of user code

	public :
            Objective(compObjective *container);
            ~Objective();
	        void initialize();
	       void end();

	       void doStep(int nStep) ;
	
	// +++++++++++++ Methods of the pItfTargetObject interface +++++++++++++
	       bool isObjectNear();

	
// Start of user code  : Additional methods

// End of user code
	

	// +++++++++++++ Access for speed parameter +++++++++++++
	    double getSpeed();
	
	    void setSpeed(double arg);
	// +++++++++++++ Access for position parameter +++++++++++++
	    vect2 getPosition();
	
	    void setPosition(vect2 arg);
};
#endif /*  Objective_H_ */
