/*
 * Simulation.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef Simulation_H_
#define Simulation_H_
#include "ReturnCode.h"
class compSimulation;

#include "ItfSimDataInterface.h"

// Start of user code  : Additional imports for Simulation
// End of user code

class Simulation : public ItfSimDataInterface {
protected :
    compSimulation* myContainer;

    // Parameters
    double expectedEndTime;
    double positionCorrection;


    // Start of user code  : Properties of Simulation
    // End of user code

public :
    Simulation(compSimulation* container);
    ~Simulation();
    void initialize();
    void end();

    ReturnCode doStep(int nStep);

    // +++++++++++++ Methods of the pItfSimData interface +++++++++++++
    double grabExpectedEndTime();

    double grabPositionCorrection();


    // Start of user code  : Additional methods
    // End of user code


    // +++++++++++++ Access for expectedEndTime parameter +++++++++++++
    double getExpectedEndTime();

    void setExpectedEndTime(double arg);
    // +++++++++++++ Access for positionCorrection parameter +++++++++++++
    double getPositionCorrection();

    void setPositionCorrection(double arg);
};
#endif /*  Simulation_H_ */
