/*
 * Simulation.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef Simulation_H_
#define Simulation_H_
#include "ReturnCode.h"
class compSimulation;
class DroSimSystem;

#include "ItfSimDataInterface.h"

// Start of user code  : Additional imports for Simulation
// End of user code

class Simulation : public ItfSimDataInterface {
protected :
    compSimulation* myContainer;

    // Parameters
    double expectedEndTime;

    DroSimSystem* systemRef_;

    // Start of user code  : Properties of Simulation
    // End of user code

public :
    Simulation(compSimulation* container);
    ~Simulation();
    void initialize();
    void end();

    ReturnCode doStep(int nStep);

    void setSystemRef(DroSimSystem* systemRef);

    string getIdentifier() const { return "simulation"; }
    
    // +++++++++++++ Methods of the pItfSimData interface +++++++++++++
    double grabExpectedEndTime();


    // Start of user code  : Additional methods
    // End of user code


    // +++++++++++++ Access for expectedEndTime parameter +++++++++++++
    double getExpectedEndTime();

    void setExpectedEndTime(double arg);
};
#endif /*  Simulation_H_ */
