/*
 * User.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef User_H_
#define User_H_
#include "Clock.h"
class compUser;

#include "ItfManageSimInterface.h"

// Start of user code  : Additional imports for User
// End of user code

class User : public ItfManageSimInterface {
protected :
    compUser* myContainer;


    // Start of user code  : Properties of User
    bool isObjectiveFound = false;
    // End of user code

public :
    User(compUser* container);
    ~User();
    void initialize();
    void end();

    int doStep(int nStep);

    // +++++++++++++ Methods of the pItfManageSimulation interface +++++++++++++
    void signalObjectiveFound(long droneID);


    // Start of user code  : Additional methods
    static double rand_range(double min, double max);
    // End of user code
};
#endif /*  User_H_ */
