/*
 * Wind.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef Wind_H_
#define Wind_H_
#include "Clock.h"
class compWind;
#include "vect2.h"

#include "ItfWindForceInterface.h"
#include "vect2.h"

// Start of user code  : Additional imports for Wind
// End of user code

class Wind  : public ItfWindForceInterface {

	protected :
              compWind *myContainer;

	// Parameters
	          double force;
	          vect2 direction;


// Start of user code  : Properties of Wind
    // End of user code

	public :
            Wind(compWind *container);
            ~Wind();
	        void initialize();
	       void end();

	       void doStep(int nStep) ;
	
	// +++++++++++++ Methods of the pItfWindForce interface +++++++++++++
	       double grabForce();

	       vect2 grabDirection();

	
// Start of user code  : Additional methods

    // End of user code
	

	// +++++++++++++ Access for force parameter +++++++++++++
	    double getForce();
	
	    void setForce(double arg);
	// +++++++++++++ Access for direction parameter +++++++++++++
	    vect2 getDirection();
	
	    void setDirection(vect2 arg);
};
#endif /*  Wind_H_ */
