/*
 * ItfTargetObjectInterface.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef ItfTargetObjectInterface_H_
#define ItfTargetObjectInterface_H_
#include <iostream>
using namespace std;

class ItfTargetObjectInterface {
	public :
           virtual bool isObjectNear() = 0;
};
#endif /* ItfTargetObjectInterface_H_ */
