/*
 * DroneData
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef DroneData_H_
#define DroneData_H_

#include <vector>
#include <iostream>
using namespace std;
// Start of user code  : Additional imports for DroneData
// End of user code

class DroneData {

	protected :
             long strategy;
             long ID;
             bool hasFound;

	public :
             DroneData();
             virtual ~DroneData();
             DroneData( long varstrategy, long varID, bool varhasFound);

	         long getStrategy () ;

	         void setStrategy (long varstrategy ) ;
	         long getID () ;

	         void setID (long varID ) ;
	         bool getHasFound () ;

	         void setHasFound (bool varhasFound ) ;
// Start of user code  : Additional methods

// End of user code

};
#endif /* DroneData_H_ */
