/*
 * User.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "compUser.h"
#include "User.h"

compUser::compUser(double aFrequency) : LeafComponent(aFrequency) {
    appli = new User(this);
    delay = 0;
    delayMax = 0;
    newValue = false;
    isActive = true;
    objectcode_ = objUser;
}

compUser::~compUser() {}

void compUser::doOneStep() {
    if (newValue) {
        delay++;
        if (delay == delayMax) {}
    }
}

ReturnCode compUser::doStep(int nStep) {
    if (newValue) {}
    readInputs();
    const auto returnCode = appli->doStep(nStep);
    if (delayMax == 0) {
        newValue = false;
    }
    else {
        newValue = true;
        delay = 0;
    }
    return returnCode;
}

void compUser::readInputs() {}

void compUser::initialize() {
    appli->initialize();
}

void compUser::end() {
    appli->end();
}

void compUser::setrItfGeoDataUser(ItfGeoDataInterface* arItfGeoDataUser) {
    appli->setrItfGeoDataUser(arItfGeoDataUser);
}

// +++++++++++++ Methods of the pItfManageSimulation interface +++++++++++++
void compUser::signalObjectiveFound(long droneID) {
    appli->signalObjectiveFound(droneID);
}

wect2 compUser::grabAssignedZone(long droneID) {
    return appli->grabAssignedZone(droneID);
}


User* compUser::getAppli() {
    return appli;
}

// +++++++++++++ Access for droneCount calculated attribute +++++++++++++
long compUser::getDroneCount() {
    return appli->getDroneCount();
}

void compUser::setDroneCount(long arg) {
    appli->setDroneCount(arg);
}
