/*
 * Manager.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "compManager.h"

#include "Manager.h"

compManager::compManager(double aFrequency) : LeafComponent( aFrequency) {
		appli = new Manager( this);
		delay = 0;
		delayMax = 0;
		newValue = false;
		isActive = true;
	}
compManager::~compManager()	{}

void compManager::doOneStep() {
		if (newValue) {
			delay++;
			if (delay == delayMax) {
			}
		}
	}

void compManager::doStep(int nStep) {	
		if (newValue) {
		}
		readInputs();
		appli->doStep(nStep);
		if (delayMax == 0) {
			newValue = false;
		} else {
			newValue = true;
			delay = 0;
		}
	}

void compManager::readInputs() {
	}
void compManager::initialize() {
		appli->initialize();
	}

void compManager::end() {
		appli->end();
	}
	
Manager *compManager::getAppli() {
		return appli;
	}
	// +++++++++++++ Access for simSpeed parameter +++++++++++++
double compManager::getSimSpeed() {
		return appli->getSimSpeed();
	}
	
void compManager::setSimSpeed(double arg) {
		appli->setSimSpeed(arg);
	}
	// +++++++++++++ Access for sweepNumber parameter +++++++++++++
long compManager::getSweepNumber() {
		return appli->getSweepNumber();
	}
	
void compManager::setSweepNumber(long arg) {
		appli->setSweepNumber(arg);
	}
	// +++++++++++++ Access for spiralNumber parameter +++++++++++++
long compManager::getSpiralNumber() {
		return appli->getSpiralNumber();
	}
	
void compManager::setSpiralNumber(long arg) {
		appli->setSpiralNumber(arg);
	}

