/* 
 * ADroneSweep.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "ADroneSweep.h"
#include "DroneSweep.h"

ADroneSweep::ADroneSweep(double aFrequency, const int ID) : compDroneSweep(aFrequency, ID) {}
ADroneSweep::~ADroneSweep() {}

void ADroneSweep::setAObjective(AObjective* pAObjective) {
    attAObjective = pAObjective;
}

void ADroneSweep::setAWind(AWind* pAWind) {
    attAWind = pAWind;
}

void ADroneSweep::readInputs() {
    appli->setObjposition(attAObjective->getObjposition());
    appli->setWindForce(attAWind->getWindForce());
    appli->setWindDirection(attAWind->getWindDirection());
}
