/* 
 * ADroneSweep.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "ADroneSweep.h"
#include "DroneSweep.h"

ADroneSweep::ADroneSweep(double aFrequency) : compDroneSweep(aFrequency) {}
ADroneSweep::~ADroneSweep() {}

void ADroneSweep::setAObjective(AObjective* pAObjective) {
    attAObjective = pAObjective;
}

void ADroneSweep::setAWind(AWind* pAWind) {
    attAWind = pAWind;
}

void ADroneSweep::readInputs() {
    for (DroneSweep* obj : appli) {
        obj->setObjposition(attAObjective->getObjposition());
        obj->setWindForce(attAWind->getWindForce());
        obj->setWindDirection(attAWind->getWindDirection());
    }
}
