/* 
 * AEnvironment.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "AEnvironment.h"
#include "Environment.h"

AEnvironment::AEnvironment(double aFrequency)	: compEnvironment(aFrequency){
		
}
AEnvironment::~AEnvironment()	{
		
}

void AEnvironment::readInputs() {
}


