/* 
 * AGeoZone.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "AGeoZone.h"
#include "GeoZone.h"

AGeoZone::AGeoZone(double aFrequency)	: compGeoZone(aFrequency){
		
}
AGeoZone::~AGeoZone()	{
		
}

void AGeoZone::readInputs() {
}


