/* 
 * AManager.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "AManager.h"
#include "Manager.h"

AManager::AManager(double aFrequency)	: compManager(aFrequency){
		
}
AManager::~AManager()	{
		
}

void AManager::readInputs() {
}


