/* 
 * AObjective.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "AObjective.h"
#include "Objective.h"

AObjective::AObjective(double aFrequency) : compObjective(aFrequency) {}
AObjective::~AObjective() {}

void AObjective::readInputs() {}
