/* 
 * ASimulation.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "ASimulation.h"
#include "Simulation.h"

ASimulation::ASimulation(double aFrequency) : compSimulation(aFrequency) {}
ASimulation::~ASimulation() {}

void ASimulation::readInputs() {}
