/* 
 * AUser.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "AUser.h"

AUser::AUser(double aFrequency) : compUser(aFrequency) {}
AUser::~AUser() {}

void AUser::readInputs() {}
