/* 
 * AWind.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "AWind.h"
#include "Wind.h"

AWind::AWind(double aFrequency)	: compWind(aFrequency){
		
}
AWind::~AWind()	{
		
}

void AWind::readInputs() {
}


