/* 
 * DroSimSystem.cpp
 * Root Component
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#include "DroSimSystem.h"
#include "Simulation.h"
#include "Wind.h"
#include "User.h"
#include "GeoZone.h"
#include "nlohmann/json.hpp"

using json = nlohmann::json;

ASimulation* DroSimSystem::get_ASimulation() {
    return instASimulation;
}

AWind* DroSimSystem::get_AWind() {
    return instAWind;
}

AUser* DroSimSystem::get_AUser() {
    return instAUser;
}

AGeoZone* DroSimSystem::get_AGeoZone() {
    return instAGeoZone;
}

AObjective* DroSimSystem::get_AObjective() {
    return instAObjective;
}

vector<ADroneSweep*> DroSimSystem::get_ADroneSweep() {
    return instADroneSweep;
}

vector<ADroneSpiral*> DroSimSystem::get_ADroneSpiral() {
    return instADroneSpiral;
}

DroSimSystem::DroSimSystem() {
    client_ = new Client("system");
    requestMessage_ = PrepareMessage("request");
    instructionMessage_ = PrepareMessage("instruction");
    initMessage_ = PrepareMessage("init");

    cpt = 0;
    
    // Simulation
    instASimulation = new ASimulation(1.0);
    leafComponents.push_back(instASimulation);
    instASimulation->setSystemRef(this);

    // Wind
    instAWind = new AWind(1.0);
    leafComponents.push_back(instAWind);
    instAWind->setSystemRef(this);

    // User
    instAUser = new AUser(1.0);
    leafComponents.push_back(instAUser);
    instAUser->setSystemRef(this);

    // GeoZone
    instAGeoZone = new AGeoZone(1.0);
    leafComponents.push_back(instAGeoZone);
    instAGeoZone->setSystemRef(this);

    // Objective
    instAObjective = new AObjective(1.0);
    leafComponents.push_back(instAObjective);
    instAObjective->setSystemRef(this);

    instAUser->setrItfGeoDataUser(instAGeoZone->getAppli());
    instAObjective->setrItfGeoDataObj(instAGeoZone->getAppli());
    
    // Initialisation des mutables
    minSpeed = 10.0;
    maxSpeed = 30.0;
    mutableSpeed = 10.0;
    maxNumberOfDrones = 10;
    speedIncrement = 2.0;
    numberOfDroneSweepIncrement = 1;
    numberOfDroneSpiralIncrement = 1;
}

DroSimSystem::~DroSimSystem() {}

json newItem(const string& objectName) {
    json item;
    item["object"] = objectName;
    item["attributes"] = json::array();
    return item;
}

json newAttribute(const string& name, const string& value) {
    json attrItem;
    attrItem[name] = value;
    return attrItem;
}

json newAttribute(const string& name, const double value) {
    json attrItem;
    attrItem[name] = value;
    return attrItem;
}

json newAttributeArray(const string& name, const vector<double>& values) {
    json attrItem;
    attrItem[name] = json::array();
    for (const auto& value : values) attrItem[name].push_back(value);
    return attrItem;
}

void DroSimSystem::initializeServer() {
    int idx = 0;

    // DroneSweep
    for (int i = 0; i < mutableNumberOfDroneSweep; i++, idx++) {
        const auto inst = new ADroneSweep(10.0, idx);
        const string& identifier = inst->getIdentifier();
        
        // Inputs & Outputs
        inst->setAObjective(instAObjective);
        inst->setAWind(instAWind);
        // Parameters
        inst->setVisionRadius(1000.0);
        // Interfaces
        inst->setrItfManageSimSweep(instAUser->getAppli());
        inst->setrItfGeoDataSweep(instAGeoZone->getAppli());
        inst->setrItfSimDataSweep(instASimulation->getAppli());
        // Lists
        instADroneSweep.emplace_back(inst);
        leafComponents.push_back(inst);
        requestingComponents_[identifier] = inst;
        // Reference to system instance
        inst->setSystemRef(this);

        // Assigned zone
        wect2 assignedZone = instAUser->grabRescaledZone(idx, 1000.0);
        inst->setSweepHeight(2000.0);

        // Prepare for init message
        json servComp;
        servComp["object"] = identifier;
        servComp["init_pos"] = { 0.0, 0.0, 0.0 };
        servComp["waypoints"] = inst->makePathWaypoints(assignedZone, 0.0);
        servComp["speed"] = 20.0;

        initMessage_["content"].push_back(servComp);

        // Subscribe variables
        AddRequest(identifier, "position");
        AddRequest(identifier, "collision");
    }

    const int err = SendMessageToServer(initMessage_);
    if (err) return;
    const json response = GetResponse();
    auto status = response["status"].template get<string>();
    if (status == "fail") {
        cout << "Init failed\nDump:\n" << response.dump(4);
        StopSim();
    }
}

void DroSimSystem::initialize() {
    initializeServer();

    // Simulation
    instASimulation->setExpectedEndTime(300000.0);

    // User

    // GeoZone
    instAGeoZone->setEnvSize(vect2(20000.0, 20000.0));
    instAGeoZone->setBottomLeftPoint(vect2(0.0, 0.0));

    // Objective
    instAObjective->setSpeedConstraint(0.0);
    instAObjective->setPosition(vect2(0, 0));

    // Calcultated attributes
    instAUser->setDroneCount(mutableNumberOfDroneSweep + mutableNumberOfDroneSpiral);

    // Initialization
    if (instASimulation->getIsActive()) instASimulation->initialize();
    if (instAWind->getIsActive()) instAWind->initialize();
    if (instAUser->getIsActive()) instAUser->initialize();
    if (instAGeoZone->getIsActive()) instAGeoZone->initialize();
    if (instAObjective->getIsActive()) instAObjective->initialize();
    for (const auto& inst : instADroneSweep)
        if (inst->getIsActive()) inst->initialize();
    for (const auto& inst : instADroneSpiral)
        if (inst->getIsActive()) inst->initialize();
    // Start of user code  : Implementation of initialize method DroSimSystem
    // End of user code
}

void DroSimSystem::end() {
    requestMessage_ = "";
    instructionMessage_ = "";
    instASimulation->end();
    instAWind->end();
    instAUser->end();
    instAGeoZone->end();
    instAObjective->end();
    for (const auto& inst : instADroneSweep) inst->end();
    instADroneSweep.clear();
    for (const auto& inst : instADroneSpiral) inst->end();
    instADroneSpiral.clear();
    for (int i = 0; i < leafComponents.size(); i++) {
        ObjectCode oc = leafComponents[i]->getObjectCode();
        if (oc == objDroneSweep || oc == objDroneSpiral)
            leafComponents.erase(leafComponents.begin() + i);
    }
    // Start of user code  : Implementation of end method DroSimSystem
    // End of user code
}

void DroSimSystem::mutateParameters(const bool isGroupSuccessful, const double averageTimeToFind) {
    cout << (isGroupSuccessful ? "Success" : "Fail") << endl;

    if (isGroupSuccessful) cout << "Average of " << (int)(averageTimeToFind / 1000 / 60 * 10) << " min to find\n";

    const double cSpeed = mutableSpeed;
    const int cNumberOfDroneSweep = mutableNumberOfDroneSweep;
    const int cNumberOfDroneSpiral = mutableNumberOfDroneSpiral;

    if (!isCurveFound || isGroupSuccessful) {
        // We overwrite the saved config as we don't need it right now
        pSpeed = cSpeed;
    }

    if (isCurveFound && isMaxFound) {
        if (isGroupSuccessful && cSpeed - speedIncrement >= minSpeed)
            mutableSpeed -= speedIncrement;
        else {
            slowConfigs.emplace_back(pSpeed, cNumberOfDroneSweep, cNumberOfDroneSpiral);

            if (cNumberOfDroneSpiral > cNumberOfDroneSweep)
                mutableNumberOfDroneSweep += numberOfDroneSweepIncrement;
            else mutableNumberOfDroneSpiral += numberOfDroneSpiralIncrement;

            // We save the current config for later comparison
            pSpeed = cSpeed;
        }
    }
    else {
        if (!isCurveFound && isGroupSuccessful) {
            // Found the first valid configuration
            slowConfigs.emplace_back(cSpeed, cNumberOfDroneSweep, cNumberOfDroneSpiral);
            isCurveFound = true;
            cout << "Curve found" << '\n';
        }
        if (cSpeed + speedIncrement <= maxSpeed)
            mutableSpeed += speedIncrement;
        else if (isCurveFound) {
            // Found the maximum speed drones need to go at
            fastConfig = make_tuple(cSpeed, cNumberOfDroneSweep, cNumberOfDroneSpiral);
            isMaxFound = true;
            cout << "Max speed found" << '\n';
            if (cNumberOfDroneSpiral > cNumberOfDroneSweep)
                mutableNumberOfDroneSweep += numberOfDroneSweepIncrement;
            else mutableNumberOfDroneSpiral += numberOfDroneSpiralIncrement;
            mutableSpeed = get<0>(slowConfigs[0]);
        }
        else {
            if (cNumberOfDroneSpiral > cNumberOfDroneSweep)
                mutableNumberOfDroneSweep += numberOfDroneSweepIncrement;
            else mutableNumberOfDroneSpiral += numberOfDroneSpiralIncrement;
            mutableSpeed = minSpeed;
        }
    }

    cout << "Trying with " << mutableNumberOfDroneSweep
        << " drone" << (mutableNumberOfDroneSweep > 1 ? "s" : "") << " making sweeps and "
        << mutableNumberOfDroneSpiral << " drone" << (mutableNumberOfDroneSpiral > 1 ? "s" : "") << " making spirals"
        << " at " << mutableSpeed << " m/s\n";
}

bool DroSimSystem::continueCondition() const {
    return mutableNumberOfDroneSweep + mutableNumberOfDroneSpiral <= maxNumberOfDrones;
}

vector<tuple<double, int, int>> DroSimSystem::getSlowConfigs() {
    return slowConfigs;
}

tuple<double, int, int> DroSimSystem::getFastConfig() {
    return fastConfig;
}

void DroSimSystem::AddRequest(const string& identifier, const string& variable) {
    for (auto& item : requestMessage_["content"])
        if (item["object"] == identifier) {
            item["attributes"].push_back(variable);
            return;
        }

    json newItem;
    newItem["object"] = identifier;
    newItem["attributes"] = {variable};
    requestMessage_["content"].push_back(newItem);
}

void DroSimSystem::AddInstruction(const string& identifier, const string& variable, const json& instruction) {
    for (auto& item : instructionMessage_["content"]) {
        if (item["object"] == identifier) {
            item["attributes"].push_back(instruction);
            return;
        }
    }

    json newItem;
    newItem["object"] = identifier;
    newItem["attributes"] = {instruction};
    instructionMessage_.push_back(newItem);
}

void DroSimSystem::AddInstruction(const string& identifier, const string& variable, const double value) {
    json instruction;
    instruction[variable] = value;
    AddInstruction(identifier,variable,instruction);
}

void DroSimSystem::AddInstruction(const string& identifier, const string& variable, const vector<double>& value) {
    json instruction;
    instruction[variable] = {value};
    AddInstruction(identifier,variable,instruction);
}

void DroSimSystem::StopSim() {
    json message = PrepareMessage("global");
    AddStopToMessage(message,{"sim"});
    const int err = SendMessageToServer(message);
    if (err) exit(err);
    const json response = GetResponse();
    if (CompareJsonField(response["status"],"fail")) exit(1);
    end();
}

json DroSimSystem::PrepareMessage(const string& type) {
    json message;
    message["type"] = type;
    message["content"] = json::array();
    return message;
}

void DroSimSystem::AddStopToMessage(json& message, const vector<string>& components) {
    json stopItem;
    stopItem["stop"] = components;
    message["content"].push_back(stopItem);
}

bool DroSimSystem::CompareJsonField(const json& field, const string& str) {
    const auto fieldvalue = GetFieldStringValue(field);
    return fieldvalue == str;
}

string DroSimSystem::GetFieldStringValue(const json& field) {
    return field.template get<string>();
}

double DroSimSystem::GetFieldDoubleValue(const json& field) {
    return field.template get<double>();
}

int DroSimSystem::SendMessageToServer(const json& message) const {
    const int ok = client_->sendToServer(message.dump());
    return ok;
}

json DroSimSystem::GetResponse() {
    const string res = client_->waitResponse();
    if (res.empty()) return "";
    json response = json::parse(res);
    auto type = GetFieldStringValue(response["type"]);
    if (type == "update")
        UpdateComponents(response);
    else if (type == "return") {
        if (CompareJsonField(response["status"],"fail")) {
            for (const auto& str : response["verbose"]) {
                auto desc = str.template get<string>();
                cout << "failed : " << desc << '\n';
            }
        }
    }
    return response;
}

void DroSimSystem::UpdateComponents(const json& response) {
    for (const auto& item : response["content"]) {
        auto identifier = item["object"].template get<string>();
        LeafComponent* requester = requestingComponents_[identifier];
        for (const auto& attribute : item["attributes"])
            for (const auto& [name, value] : attribute.items()) {
                if (value.is_array()) { // l'attribut est un tableau (position, direction...)
                    vector<double> doublevalues;
                    for (const auto& v : value)
                        doublevalues.push_back(v.template get<double>());
                    requester->getRequestResponseArray(name, doublevalues);
                }
                else { // l'attribut est une valeur
                    auto doublevalue = value.template get<double>();
                    requester->getRequestResponse(name, doublevalue);
                }
            }
        if (item.contains("other")) UpdateCustomProperties_Local(item["other"]);
    }
    UpdateCustomProperties_Global(response);
}

void DroSimSystem::UpdateCustomProperties_Local(const json& other) {
    // begin user code
    
    // end user code
}

void DroSimSystem::UpdateCustomProperties_Global(const json& response) {
    // begin user code
    json message = PrepareMessage("global");
    
    vector<string> stopList;
    for (const auto& item : response["content"]) {
        if (!item.contains("other")) break;
        const json& other = item["other"];
        
        // collisions
        for (const auto& identifier : other["collisions"])
            if (find(stopList.begin(), stopList.end(), identifier) == stopList.end())
                stopList.push_back(identifier);
    }
    
    AddStopToMessage(message, stopList);

    const int err = SendMessageToServer(message);
    if (err) StopSim();
    const json res = GetResponse();
    if (CompareJsonField(res["status"],"fail")) StopSim();
    
    // end user code
}